### ISSUE TITLE
Download issue?

### ISSUE THREAD

**Issue by JQNorman** [TannerNelson16/playlistdl#1]
Not exactly sure what I am doing wrong here, I have tried to configure the downloads volume on my unraid server a  bunch of different ways, and for whatever reason when the file is done making the .zip it just auto downloads the zip to the PC im on and not the server?  I just cant seem to get it to download to the host container pc vs the one im on?

**Comment by TannerNelson16** [comment]
You're not doing anything wrong. It's actually functioning as intended. Currently, the audio files are downloaded to the client machine and erased from the server. Download to the server is the next feature on the list. I'm planning to add an 'admin' button that lets you log in with credentials defined in the docker compose file and choose to download to your server. I want to put this behind a login screen in case other 'non-admin' users are accessing the service. Sorry for any confusion here. I'll update the documentation with this info and hope to work on this feature soon.

**Comment by JQNorman** [comment]
That would be a great feature. I also think if you allow it to post-download the .zip to the server machine, extracting it into a folder that Lidarr could monitor to integrate into the ARR stack would be clutch. LidaTube does something similar, but it is strictly for YouTube, that I am aware of. LidaTube actually scans your Lidarr wanted list and then does your process for YTD. Being able to pull Spotify playlists into Lidar would be a game changer.

**Comment by TannerNelson16** [comment]
Just pushed this feature! Give it a try and let me know what you think. If any instructions are unclear, let me know.
