### ISSUE TITLE
Cannot get the download environment variables to work.

### ISSUE THREAD

**Issue by Miles-Beck** [TannerNelson16/playlistdl#4]
Can you provide an example of how to use them?

**Comment by TannerNelson16** [comment]
Sure thing. I recognize it could be confusing. Maybe I should look into clarifying this in the README. Essentially the only variable you need to change in the docker compose file are the ADMIN_USERNAME and ADMIN_PASSWORD.  Those are simply chosen in the docker-compose file. They don't reference anything else. 

The AUDIO_DOWNLOAD_PATH is only changed in your .env file. If you don't already have a .env file, you can either make a new one with this variable declared, or copy mine from the repository. In any case, it simply looks like this:

AUDIO_DOWNLOAD_PATH=/your/folder/path #(obviously with your folder path inserted here)

**Comment by Miles-Beck** [comment]
Thanks, I did not realize I needed and env file as well.
