### ISSUE TITLE
What CPU architecture does this support?

### ISSUE THREAD

**Issue by Miles-Beck** [TannerNelson16/playlistdl#5]
I presume this will not work for me as after I got the environment file set up I saw the below errors after the container was created. You may want to add what is supported in the Readme.

! playlistdl The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested 0.0s 
Attaching to playlistdl
playlistdl  | exec /opt/venv/bin/python3: exec format error
playlistdl exited with code 0
playlistdl  | exec /opt/venv/bin/python3: exec format error
playlistdl  | exec /opt/venv/bin/python3: exec format error
playlistdl  | exec /opt/venv/bin/python3: exec format error
playlistdl  | exec /opt/venv/bin/python3: exec format error
playlistdl  | exec /opt/venv/bin/python3: exec format error
playlistdl  | exec /opt/venv/bin/python3: exec format error
playlistdl  | exec /opt/venv/bin/python3: exec format error
playlistdl  | exec /opt/venv/bin/python3: exec format error
playlistdl  | exec /opt/venv/bin/python3: exec format error

**Comment by TannerNelson16** [comment]
Hm, it looks like you're trying to build this from source code (which you shouldn't have to). With docker images, the architecture of your machine shouldn't matter. Do you by chance have a "build: ." line in your docker compose? If not, what command are you using to build the container?

**Comment by Miles-Beck** [comment]
I don't believe I have the build line in my compose file but I can check later.  To start the container I am using 'docker compose up'.

**Comment by TannerNelson16** [comment]
Ok, sorry. I think this was my misunderstanding about docker. I don't have any arm64 devices to ever see this issue, but it looks like I can rebuild the docker image with both architectures available. I've pushed it to docker hub, so it should automatically update when you build the image again. The build took quite some time, and I don't have any devices to test this on, so your mileage may vary. Let me know how it goes.

**Comment by Miles-Beck** [comment]
I got a similar error when trying again. This is on a Rasberry Pi 5.

~/Docker/playlistdl $ docker compose up
[+] Running 1/0
 ✔ Container playlistdl  Created                                                                                                                       0.0s 
Attaching to playlistdl
playlistdl  | exec /opt/venv/bin/python3: exec format error
playlistdl exited with code 0
playlistdl  | exec /opt/venv/bin/python3: exec format error
playlistdl  | exec /opt/venv/bin/python3: exec format error
playlistdl  | exec /opt/venv/bin/python3: exec format error
playlistdl  | exec /opt/venv/bin/python3: exec format error
playlistdl  | exec /opt/venv/bin/python3: exec format error
playlistdl  | exec /opt/venv/bin/python3: exec format error
playlistdl  | exec /opt/venv/bin/python3: exec format error
playlistdl  | exec /opt/venv/bin/python3: exec format error
playlistdl  | exec /opt/venv/bin/python3: exec format error
playlistdl  | exec /opt/venv/bin/python3: exec format error
playlistdl  | exec /opt/venv/bin/python3: exec format error

**Comment by TannerNelson16** [comment]
That's odd. From what I understand, this should fix the issue. I would amend my previous instructions to say you need to first delete the container and then rebuild it. Or do a "docker compose pull" command. Have you already tried either of these?

**Comment by Miles-Beck** [comment]
I just did a 'docker compost pull' and that  has fixed the issue. Not sure why it did not work before but I am glad it's working now. Thanks for your help.

**Comment by TannerNelson16** [comment]
No problem. Glad you were able to get it working!
